### PR TITLE
update favicons

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/kubesphere/dev-guide/issues/136

### CODE REVIEW

**Comment by Arhell** [comment]
/assign @rayzhou2017
https://realfavicongenerator.net/favicon_checker?protocol=https&site=deploy-preview-137--kubesphere-dev-guide.netlify.app%2Fextension-dev-guide%2Fzh%2F#.YxfHuHbP23A

**Comment by rayzhou2017** [comment]
Thanks @Arhell! I found the icon at somewhere (for example, the doc website as the screenshot shown) is white. Is there any reason for it? 
Screenshot 2022-09-07 at 6 55 21 AM
As you can see from the screenshot, the green one is expected.

**Comment by Arhell** [comment]
> Thanks @Arhell! I found the icon at somewhere (for example, the doc website as the screenshot shown) is white. Is there any reason for it? Screenshot 2022-09-07 at 6 55 21 AM As you can see from the screenshot, the green one is expected.

Are you using safari?

**Comment by rayzhou2017** [comment]
> > Thanks @Arhell! I found the icon at somewhere (for example, the doc website as the screenshot shown) is white. Is there any reason for it? Screenshot 2022-09-07 at 6 55 21 AM As you can see from the screenshot, the green one is expected.
> 
> Are you using safari? https://github.com/kubesphere/dev-guide/pull/137/files#diff-acf7d36ba6c864474a9bf900f0efc50b868c1c586c66c601a337cf37f6396186R8

yes. Just checked FF and Chrome. Both are green. Any reason why it is white in Safari?

**Comment by Arhell** [comment]
> 



> > > Thanks @Arhell! I found the icon at somewhere (for example, the doc website as the screenshot shown) is white. Is there any reason for it? Screenshot 2022-09-07 at 6 55 21 AM As you can see from the screenshot, the green one is expected.
> > 
> > 
> > Are you using safari? https://github.com/kubesphere/dev-guide/pull/137/files#diff-acf7d36ba6c864474a9bf900f0efc50b868c1c586c66c601a337cf37f6396186R8
> 
> yes. Just checked FF and Chrome. Both are green. Any reason why it is white in Safari?

Corrected, I will also correct it on the main site

**Pull request merged**
